networks:
  nl2etl-network:
    name: nl2etl-network


volumes:
  minio-data:
    name: minio-data
  shared_data:
    name: shared_data
  postgresql-data:
    name: postgresql-data


services:
  app:
    build:
      context: ./server
      no_cache: true
    container_name: nl2etl_app
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
      - ./scripts:/app/scripts
      - ./server:/app/server
      - shared_data:/shared
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=${GROQ_MODEL:-openai/gpt-oss-120b}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_HOST=${MINIO_HOST:-host.docker.internal:9000}
      - MINIO_BUCKET=${MINIO_BUCKET:-nl2etl}
      - OUTPUT_DIR=/app/output
      - SCRIPTS_DIR=/app/scripts
      - SANDBOX_IMAGE=nl2etl_sandbox
    depends_on:
      sandbox:
        condition: service_completed_successfully
    networks:
      - nl2etl-network

  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_DB=nl2etl_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - postgresql-data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - nl2etl-network

  sandbox:
    build: ./sandbox
    image: nl2etl_sandbox
    container_name: nl2etl_sandbox_builder
    command: echo "Sandbox container is running"
    volumes:
      - shared_data:/shared

  minio:
    image: quay.io/minio/minio:latest
    container_name: nl2etl_file_storage
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9090"
    volumes:
      - minio-data:/data
    restart: always
    networks:
      - nl2etl-network
